IS_REMOTE = "IS_REMOTE"

SOURCE_DIRECTORY = "SOURCE_DIRECTORY"
ARCHIVE_DIRECTORY = "ARCHIVE_DIRECTORY"
REMOTE_ERROR_DIRECTORY = "REMOTE_ERROR_DIRECTORY"
SOURCE_HOST = "SOURCE_HOST"
SOURCE_PORT = "SOURCE_PORT"
SOURCE_USERNAME = "SOURCE_USERNAME"
SOURCE_SECRET = "SOURCE_SECRET"

TARGET_DIRECTORY = "TARGET_DIRECTORY"
ERROR_DIRECTORY = "ERROR_DIRECTORY"
OUTPUT_DIRECTORY = "OUTPUT_DIRECTORY"
LOG_DIRECTORY = "LOG_DIRECTORY"
FILE_EXTENSIONS = "FILE_EXTENSIONS"

NOTIFICATIONS = "NOTIFICATIONS"
SMTP_HOST = "SMTP_HOST"
SMTP_PORT = "SMTP_PORT"
FROM_EMAIL = "FROM_EMAIL"
RECIPIENT_EMAIL = "RECIPIENT_EMAIL"
EMAIL_SUBJECT = "EMAIL_SUBJECT"
EMAIL_BODY = "EMAIL_BODY"
EMAIL_DELIVERY_ON = "EMAIL_DELIVERY_ON"

SCHEDULE = "SCHEDULE"
ACTION = "ACTION"

EVERY = "EVERY"
TIME_UNIT = "TIME_UNIT"
AT = "AT"

